GRANT FLASHBACK ON oc_grant_fix_testing2.test_table2 TO oc_grant_fix_testing;
GRANT ALTER ON oc_grant_fix_testing.test_table2 TO oc_grant_fix_testing2;
GRANT ALTER ON oc_grant_fix_testing.test_table2 TO PUBLIC;
GRANT DEBUG ON oc_grant_fix_testing.test_table2 TO oc_grant_fix_testing2;
GRANT DEBUG ON oc_grant_fix_testing.test_table2 TO PUBLIC;
GRANT DELETE ON oc_grant_fix_testing.test_table2 TO oc_grant_fix_testing2;
GRANT DELETE ON oc_grant_fix_testing.test_table2 TO PUBLIC;
GRANT FLASHBACK ON oc_grant_fix_testing.test_table2 TO oc_grant_fix_testing2;
GRANT FLASHBACK ON oc_grant_fix_testing.test_table2 TO PUBLIC;
GRANT INDEX ON oc_grant_fix_testing.test_table2 TO oc_grant_fix_testing2;
GRANT INDEX ON oc_grant_fix_testing.test_table2 TO PUBLIC;
GRANT INSERT ON oc_grant_fix_testing.test_table2 TO oc_grant_fix_testing2;
GRANT INSERT ON oc_grant_fix_testing.test_table2 TO PUBLIC;
GRANT ON COMMIT REFRESH ON oc_grant_fix_testing.test_table2 TO oc_grant_fix_testing2;
GRANT ON COMMIT REFRESH ON oc_grant_fix_testing.test_table2 TO PUBLIC;
GRANT QUERY REWRITE ON oc_grant_fix_testing.test_table2 TO oc_grant_fix_testing2;
GRANT QUERY REWRITE ON oc_grant_fix_testing.test_table2 TO PUBLIC;
GRANT REFERENCES ON oc_grant_fix_testing.test_table2 TO oc_grant_fix_testing2;
GRANT REFERENCES ON oc_grant_fix_testing.test_table2 TO PUBLIC;
GRANT SELECT ON oc_grant_fix_testing.test_table2 TO oc_grant_fix_testing2;
GRANT SELECT ON oc_grant_fix_testing.test_table2 TO PUBLIC;
GRANT UPDATE ON oc_grant_fix_testing.test_table2 TO oc_grant_fix_testing2;
GRANT UPDATE ON oc_grant_fix_testing.test_table2 TO PUBLIC;