GRANT CREATE ANY MATERIALIZED VIEW TO oc_grant_testing WITH ADMIN OPTION;
GRANT CREATE SESSION TO oc_grant_testing;
GRANT CREATE TABLE TO oc_grant_testing;
GRANT UNLIMITED TABLESPACE TO oc_grant_testing;